# Generated by Django 2.2.9 on 2020-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200307_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
