# Generated by Django 2.2.9 on 2020-03-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
    ]
